// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzaflfrbuugucbuevfxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWZsZnJidXVndWNidWV2ZnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzE1MzIsImV4cCI6MjA1OTQ0NzUzMn0.rro6QS8GjrRSdDkgO4ZzDg_dpLDaIVswLQH8f1fRs_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);